// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	dtos "github.com/edgexfoundry/go-mod-core-contracts/v4/dtos"
	errors "github.com/edgexfoundry/go-mod-core-contracts/v4/errors"

	mock "github.com/stretchr/testify/mock"

	time "time"

	xrtmodels "github.com/IOTechSystems/go-mod-central-ext/v4/pkg/xrtmodels"
)

// EdgeClient is an autogenerated mock type for the EdgeClient type
type EdgeClient struct {
	mock.Mock
}

// AddDevice provides a mock function with given fields: ctx, device
func (_m *EdgeClient) AddDevice(ctx context.Context, device dtos.Device) errors.EdgeX {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for AddDevice")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Device) errors.EdgeX); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// AddDeviceProfile provides a mock function with given fields: ctx, device
func (_m *EdgeClient) AddDeviceProfile(ctx context.Context, device dtos.DeviceProfile) errors.EdgeX {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for AddDeviceProfile")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, dtos.DeviceProfile) errors.EdgeX); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// AddDiscoveredDevice provides a mock function with given fields: ctx, device
func (_m *EdgeClient) AddDiscoveredDevice(ctx context.Context, device dtos.Device) errors.EdgeX {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for AddDiscoveredDevice")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Device) errors.EdgeX); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// AddSchedule provides a mock function with given fields: ctx, schedule
func (_m *EdgeClient) AddSchedule(ctx context.Context, schedule xrtmodels.Schedule) errors.EdgeX {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for AddSchedule")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, xrtmodels.Schedule) errors.EdgeX); ok {
		r0 = rf(ctx, schedule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// AllDeviceProfiles provides a mock function with given fields: ctx
func (_m *EdgeClient) AllDeviceProfiles(ctx context.Context) ([]string, errors.EdgeX) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllDeviceProfiles")
	}

	var r0 []string
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, errors.EdgeX)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) errors.EdgeX); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// AllDevices provides a mock function with given fields: ctx
func (_m *EdgeClient) AllDevices(ctx context.Context) ([]string, errors.EdgeX) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllDevices")
	}

	var r0 []string
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, errors.EdgeX)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) errors.EdgeX); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// AllSchedules provides a mock function with given fields: ctx
func (_m *EdgeClient) AllSchedules(ctx context.Context) ([]string, errors.EdgeX) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllSchedules")
	}

	var r0 []string
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context) ([]string, errors.EdgeX)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) errors.EdgeX); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchAddDevices provides a mock function with given fields: ctx, devices
func (_m *EdgeClient) BatchAddDevices(ctx context.Context, devices []dtos.Device) ([]xrtmodels.BatchItemResult, errors.EdgeX) {
	ret := _m.Called(ctx, devices)

	if len(ret) == 0 {
		panic("no return value specified for BatchAddDevices")
	}

	var r0 []xrtmodels.BatchItemResult
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, []dtos.Device) ([]xrtmodels.BatchItemResult, errors.EdgeX)); ok {
		return rf(ctx, devices)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []dtos.Device) []xrtmodels.BatchItemResult); ok {
		r0 = rf(ctx, devices)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xrtmodels.BatchItemResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []dtos.Device) errors.EdgeX); ok {
		r1 = rf(ctx, devices)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchAddSchedules provides a mock function with given fields: ctx, schedules
func (_m *EdgeClient) BatchAddSchedules(ctx context.Context, schedules []xrtmodels.Schedule) ([]xrtmodels.BatchItemResult, errors.EdgeX) {
	ret := _m.Called(ctx, schedules)

	if len(ret) == 0 {
		panic("no return value specified for BatchAddSchedules")
	}

	var r0 []xrtmodels.BatchItemResult
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, []xrtmodels.Schedule) ([]xrtmodels.BatchItemResult, errors.EdgeX)); ok {
		return rf(ctx, schedules)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []xrtmodels.Schedule) []xrtmodels.BatchItemResult); ok {
		r0 = rf(ctx, schedules)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xrtmodels.BatchItemResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []xrtmodels.Schedule) errors.EdgeX); ok {
		r1 = rf(ctx, schedules)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchDeleteDevices provides a mock function with given fields: ctx, names
func (_m *EdgeClient) BatchDeleteDevices(ctx context.Context, names []string) ([]xrtmodels.BatchItemResult, errors.EdgeX) {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for BatchDeleteDevices")
	}

	var r0 []xrtmodels.BatchItemResult
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]xrtmodels.BatchItemResult, errors.EdgeX)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []xrtmodels.BatchItemResult); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xrtmodels.BatchItemResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) errors.EdgeX); ok {
		r1 = rf(ctx, names)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchDeleteSchedulesByDevice provides a mock function with given fields: ctx, deviceName
func (_m *EdgeClient) BatchDeleteSchedulesByDevice(ctx context.Context, deviceName string) ([]xrtmodels.BatchItemResult, errors.EdgeX) {
	ret := _m.Called(ctx, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for BatchDeleteSchedulesByDevice")
	}

	var r0 []xrtmodels.BatchItemResult
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]xrtmodels.BatchItemResult, errors.EdgeX)); ok {
		return rf(ctx, deviceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []xrtmodels.BatchItemResult); ok {
		r0 = rf(ctx, deviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xrtmodels.BatchItemResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, deviceName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchDeleteSchedulesByNames provides a mock function with given fields: ctx, names
func (_m *EdgeClient) BatchDeleteSchedulesByNames(ctx context.Context, names []string) ([]xrtmodels.BatchItemResult, errors.EdgeX) {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for BatchDeleteSchedulesByNames")
	}

	var r0 []xrtmodels.BatchItemResult
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]xrtmodels.BatchItemResult, errors.EdgeX)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []xrtmodels.BatchItemResult); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xrtmodels.BatchItemResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) errors.EdgeX); ok {
		r1 = rf(ctx, names)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchReadAllDevices provides a mock function with given fields: ctx
func (_m *EdgeClient) BatchReadAllDevices(ctx context.Context) ([]*xrtmodels.DeviceInfo, errors.EdgeX) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BatchReadAllDevices")
	}

	var r0 []*xrtmodels.DeviceInfo
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context) ([]*xrtmodels.DeviceInfo, errors.EdgeX)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*xrtmodels.DeviceInfo); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xrtmodels.DeviceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) errors.EdgeX); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchReadAllSchedules provides a mock function with given fields: ctx
func (_m *EdgeClient) BatchReadAllSchedules(ctx context.Context) ([]*xrtmodels.Schedule, errors.EdgeX) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BatchReadAllSchedules")
	}

	var r0 []*xrtmodels.Schedule
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context) ([]*xrtmodels.Schedule, errors.EdgeX)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*xrtmodels.Schedule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xrtmodels.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) errors.EdgeX); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchReadDevicesByNames provides a mock function with given fields: ctx, names
func (_m *EdgeClient) BatchReadDevicesByNames(ctx context.Context, names []string) ([]*xrtmodels.DeviceInfo, errors.EdgeX) {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for BatchReadDevicesByNames")
	}

	var r0 []*xrtmodels.DeviceInfo
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*xrtmodels.DeviceInfo, errors.EdgeX)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*xrtmodels.DeviceInfo); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xrtmodels.DeviceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) errors.EdgeX); ok {
		r1 = rf(ctx, names)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchReadDevicesByPattern provides a mock function with given fields: ctx, pattern
func (_m *EdgeClient) BatchReadDevicesByPattern(ctx context.Context, pattern string) ([]*xrtmodels.DeviceInfo, errors.EdgeX) {
	ret := _m.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for BatchReadDevicesByPattern")
	}

	var r0 []*xrtmodels.DeviceInfo
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*xrtmodels.DeviceInfo, errors.EdgeX)); ok {
		return rf(ctx, pattern)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*xrtmodels.DeviceInfo); ok {
		r0 = rf(ctx, pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xrtmodels.DeviceInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, pattern)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchReadSchedulesByDevice provides a mock function with given fields: ctx, deviceName
func (_m *EdgeClient) BatchReadSchedulesByDevice(ctx context.Context, deviceName string) ([]*xrtmodels.Schedule, errors.EdgeX) {
	ret := _m.Called(ctx, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for BatchReadSchedulesByDevice")
	}

	var r0 []*xrtmodels.Schedule
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*xrtmodels.Schedule, errors.EdgeX)); ok {
		return rf(ctx, deviceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*xrtmodels.Schedule); ok {
		r0 = rf(ctx, deviceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xrtmodels.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, deviceName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchReadSchedulesByNames provides a mock function with given fields: ctx, names
func (_m *EdgeClient) BatchReadSchedulesByNames(ctx context.Context, names []string) ([]*xrtmodels.Schedule, errors.EdgeX) {
	ret := _m.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for BatchReadSchedulesByNames")
	}

	var r0 []*xrtmodels.Schedule
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*xrtmodels.Schedule, errors.EdgeX)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*xrtmodels.Schedule); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xrtmodels.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) errors.EdgeX); ok {
		r1 = rf(ctx, names)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// BatchReadSchedulesByPattern provides a mock function with given fields: ctx, pattern
func (_m *EdgeClient) BatchReadSchedulesByPattern(ctx context.Context, pattern string) ([]*xrtmodels.Schedule, errors.EdgeX) {
	ret := _m.Called(ctx, pattern)

	if len(ret) == 0 {
		panic("no return value specified for BatchReadSchedulesByPattern")
	}

	var r0 []*xrtmodels.Schedule
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*xrtmodels.Schedule, errors.EdgeX)); ok {
		return rf(ctx, pattern)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*xrtmodels.Schedule); ok {
		r0 = rf(ctx, pattern)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*xrtmodels.Schedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, pattern)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// Close provides a mock function with no fields
func (_m *EdgeClient) Close() errors.EdgeX {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func() errors.EdgeX); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// DeleteDeviceByName provides a mock function with given fields: ctx, name
func (_m *EdgeClient) DeleteDeviceByName(ctx context.Context, name string) errors.EdgeX {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeviceByName")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) errors.EdgeX); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// DeleteDeviceProfileByName provides a mock function with given fields: ctx, name
func (_m *EdgeClient) DeleteDeviceProfileByName(ctx context.Context, name string) errors.EdgeX {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeviceProfileByName")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) errors.EdgeX); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// DeleteScheduleByName provides a mock function with given fields: ctx, scheduleName
func (_m *EdgeClient) DeleteScheduleByName(ctx context.Context, scheduleName string) errors.EdgeX {
	ret := _m.Called(ctx, scheduleName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteScheduleByName")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) errors.EdgeX); ok {
		r0 = rf(ctx, scheduleName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// DeviceByName provides a mock function with given fields: ctx, name
func (_m *EdgeClient) DeviceByName(ctx context.Context, name string) (xrtmodels.DeviceInfo, errors.EdgeX) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeviceByName")
	}

	var r0 xrtmodels.DeviceInfo
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) (xrtmodels.DeviceInfo, errors.EdgeX)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) xrtmodels.DeviceInfo); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(xrtmodels.DeviceInfo)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// DeviceProfileByName provides a mock function with given fields: ctx, name
func (_m *EdgeClient) DeviceProfileByName(ctx context.Context, name string) (dtos.DeviceProfile, errors.EdgeX) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for DeviceProfileByName")
	}

	var r0 dtos.DeviceProfile
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) (dtos.DeviceProfile, errors.EdgeX)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dtos.DeviceProfile); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(dtos.DeviceProfile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// DiscoverComponents provides a mock function with given fields: ctx, category, subscribeTimeout
func (_m *EdgeClient) DiscoverComponents(ctx context.Context, category string, subscribeTimeout time.Duration) ([]xrtmodels.MultiComponentsResponse, errors.EdgeX) {
	ret := _m.Called(ctx, category, subscribeTimeout)

	if len(ret) == 0 {
		panic("no return value specified for DiscoverComponents")
	}

	var r0 []xrtmodels.MultiComponentsResponse
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) ([]xrtmodels.MultiComponentsResponse, errors.EdgeX)); ok {
		return rf(ctx, category, subscribeTimeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) []xrtmodels.MultiComponentsResponse); ok {
		r0 = rf(ctx, category, subscribeTimeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]xrtmodels.MultiComponentsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Duration) errors.EdgeX); ok {
		r1 = rf(ctx, category, subscribeTimeout)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// ReadDeviceResources provides a mock function with given fields: ctx, deviceName, resourceNames
func (_m *EdgeClient) ReadDeviceResources(ctx context.Context, deviceName string, resourceNames []string) (xrtmodels.MultiResourcesResult, errors.EdgeX) {
	ret := _m.Called(ctx, deviceName, resourceNames)

	if len(ret) == 0 {
		panic("no return value specified for ReadDeviceResources")
	}

	var r0 xrtmodels.MultiResourcesResult
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (xrtmodels.MultiResourcesResult, errors.EdgeX)); ok {
		return rf(ctx, deviceName, resourceNames)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) xrtmodels.MultiResourcesResult); ok {
		r0 = rf(ctx, deviceName, resourceNames)
	} else {
		r0 = ret.Get(0).(xrtmodels.MultiResourcesResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) errors.EdgeX); ok {
		r1 = rf(ctx, deviceName, resourceNames)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// ScanDevice provides a mock function with given fields: ctx, device, options, timeout
func (_m *EdgeClient) ScanDevice(ctx context.Context, device dtos.Device, options map[string]interface{}, timeout time.Duration) errors.EdgeX {
	ret := _m.Called(ctx, device, options, timeout)

	if len(ret) == 0 {
		panic("no return value specified for ScanDevice")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Device, map[string]interface{}, time.Duration) errors.EdgeX); ok {
		r0 = rf(ctx, device, options, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// ScanDeviceWithResult provides a mock function with given fields: ctx, device, options, timeout
func (_m *EdgeClient) ScanDeviceWithResult(ctx context.Context, device dtos.Device, options map[string]interface{}, timeout time.Duration) (string, errors.EdgeX) {
	ret := _m.Called(ctx, device, options, timeout)

	if len(ret) == 0 {
		panic("no return value specified for ScanDeviceWithResult")
	}

	var r0 string
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Device, map[string]interface{}, time.Duration) (string, errors.EdgeX)); ok {
		return rf(ctx, device, options, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Device, map[string]interface{}, time.Duration) string); ok {
		r0 = rf(ctx, device, options, timeout)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dtos.Device, map[string]interface{}, time.Duration) errors.EdgeX); ok {
		r1 = rf(ctx, device, options, timeout)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// ScheduleByName provides a mock function with given fields: ctx, name
func (_m *EdgeClient) ScheduleByName(ctx context.Context, name string) (xrtmodels.Schedule, errors.EdgeX) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ScheduleByName")
	}

	var r0 xrtmodels.Schedule
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) (xrtmodels.Schedule, errors.EdgeX)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) xrtmodels.Schedule); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(xrtmodels.Schedule)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) errors.EdgeX); ok {
		r1 = rf(ctx, name)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// SetResponseTimeout provides a mock function with given fields: responseTimeout
func (_m *EdgeClient) SetResponseTimeout(responseTimeout time.Duration) {
	_m.Called(responseTimeout)
}

// TriggerDiscovery provides a mock function with given fields: ctx
func (_m *EdgeClient) TriggerDiscovery(ctx context.Context) errors.EdgeX {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TriggerDiscovery")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context) errors.EdgeX); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// UpdateComponent provides a mock function with given fields: ctx, name, config
func (_m *EdgeClient) UpdateComponent(ctx context.Context, name string, config map[string]interface{}) errors.EdgeX {
	ret := _m.Called(ctx, name, config)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponent")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) errors.EdgeX); ok {
		r0 = rf(ctx, name, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// UpdateDevice provides a mock function with given fields: ctx, device
func (_m *EdgeClient) UpdateDevice(ctx context.Context, device dtos.Device) errors.EdgeX {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDevice")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, dtos.Device) errors.EdgeX); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// UpdateDeviceProfile provides a mock function with given fields: ctx, device
func (_m *EdgeClient) UpdateDeviceProfile(ctx context.Context, device dtos.DeviceProfile) errors.EdgeX {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeviceProfile")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, dtos.DeviceProfile) errors.EdgeX); ok {
		r0 = rf(ctx, device)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// UpdateLuaScript provides a mock function with given fields: ctx, luaScript
func (_m *EdgeClient) UpdateLuaScript(ctx context.Context, luaScript string) errors.EdgeX {
	ret := _m.Called(ctx, luaScript)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLuaScript")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string) errors.EdgeX); ok {
		r0 = rf(ctx, luaScript)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// UpdateSchedule provides a mock function with given fields: ctx, schedule
func (_m *EdgeClient) UpdateSchedule(ctx context.Context, schedule xrtmodels.Schedule) errors.EdgeX {
	ret := _m.Called(ctx, schedule)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSchedule")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, xrtmodels.Schedule) errors.EdgeX); ok {
		r0 = rf(ctx, schedule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// WriteDeviceResources provides a mock function with given fields: ctx, deviceName, resourceValuePairs, options
func (_m *EdgeClient) WriteDeviceResources(ctx context.Context, deviceName string, resourceValuePairs map[string]interface{}, options map[string]interface{}) errors.EdgeX {
	ret := _m.Called(ctx, deviceName, resourceValuePairs, options)

	if len(ret) == 0 {
		panic("no return value specified for WriteDeviceResources")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, map[string]interface{}) errors.EdgeX); ok {
		r0 = rf(ctx, deviceName, resourceValuePairs, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// NewEdgeClient creates a new instance of EdgeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEdgeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *EdgeClient {
	mock := &EdgeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
