// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	errors "github.com/edgexfoundry/go-mod-core-contracts/v4/errors"

	mock "github.com/stretchr/testify/mock"

	models "github.com/IOTechSystems/go-mod-edge-connect-client/v4/pkg/xrt/sparkplug/models"

	time "time"

	xrtmodels "github.com/IOTechSystems/go-mod-central-ext/v4/pkg/xrtmodels"
)

// SparkplugClient is an autogenerated mock type for the SparkplugClient type
type SparkplugClient struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *SparkplugClient) Close() errors.EdgeX {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func() errors.EdgeX); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// Nodes provides a mock function with no fields
func (_m *SparkplugClient) Nodes() []models.NodeInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nodes")
	}

	var r0 []models.NodeInfo
	if rf, ok := ret.Get(0).(func() []models.NodeInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.NodeInfo)
		}
	}

	return r0
}

// ReadDeviceResources provides a mock function with given fields: ctx, node, device, resourceNames
func (_m *SparkplugClient) ReadDeviceResources(ctx context.Context, node models.NodeKey, device string, resourceNames []string) (xrtmodels.MultiResourcesResult, errors.EdgeX) {
	ret := _m.Called(ctx, node, device, resourceNames)

	if len(ret) == 0 {
		panic("no return value specified for ReadDeviceResources")
	}

	var r0 xrtmodels.MultiResourcesResult
	var r1 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, models.NodeKey, string, []string) (xrtmodels.MultiResourcesResult, errors.EdgeX)); ok {
		return rf(ctx, node, device, resourceNames)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.NodeKey, string, []string) xrtmodels.MultiResourcesResult); ok {
		r0 = rf(ctx, node, device, resourceNames)
	} else {
		r0 = ret.Get(0).(xrtmodels.MultiResourcesResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.NodeKey, string, []string) errors.EdgeX); ok {
		r1 = rf(ctx, node, device, resourceNames)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(errors.EdgeX)
		}
	}

	return r0, r1
}

// Rebirth provides a mock function with no fields
func (_m *SparkplugClient) Rebirth() errors.EdgeX {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Rebirth")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func() errors.EdgeX); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// SetRequestTimeout provides a mock function with given fields: requestTimeout
func (_m *SparkplugClient) SetRequestTimeout(requestTimeout time.Duration) {
	_m.Called(requestTimeout)
}

// WriteDeviceResources provides a mock function with given fields: ctx, node, device, resourceValuePairs, options
func (_m *SparkplugClient) WriteDeviceResources(ctx context.Context, node models.NodeKey, device string, resourceValuePairs map[string]interface{}, options map[string]interface{}) errors.EdgeX {
	ret := _m.Called(ctx, node, device, resourceValuePairs, options)

	if len(ret) == 0 {
		panic("no return value specified for WriteDeviceResources")
	}

	var r0 errors.EdgeX
	if rf, ok := ret.Get(0).(func(context.Context, models.NodeKey, string, map[string]interface{}, map[string]interface{}) errors.EdgeX); ok {
		r0 = rf(ctx, node, device, resourceValuePairs, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(errors.EdgeX)
		}
	}

	return r0
}

// NewSparkplugClient creates a new instance of SparkplugClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSparkplugClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *SparkplugClient {
	mock := &SparkplugClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
